### ISSUE TITLE
[portal] Activate support for lists of values in the sampling-height and file-size filters

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/data#104]
This functionality can now be activated thanks to the recent enhancements to our SPARQL engine (support for fast queries with boolean-OR filters). At the moment, we only allow min-, max- interval-, and single-value filters in the front end. Note that multiple FILTER clauses are supported now, which can simplify implementation (one can use one dedicated FILTER for sampling height, and one for file size). Please remember to update the help text in the widgets.

**Comment by DrMaggie** [comment]
Can you give some examples of SPARQL code that combines filters of the type you mention?
