### ISSUE TITLE
temporal filters return non filtered results

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/data#114]
Reproduce error with the following two steps:
Add filters to the data portal app:
- Projcet: icos
- Theme: Ecosysystem data
- Data type: ICOS ETC Archive Product
- Data level : 2

Add temporal filters data sample:
from 2018-01-01 to 2020-01-01 -> `no results`
change to 2020-01-02 -> `correct results are returned`

The happens because data sampling time is converted from local timezone to UTC. So technically speaking the above result is correct, but for the user difficult to understand.

**Comment by mirzov** [comment]
Judging by the description, the behavior is correct, as data object containing only the data for 2018 does satisfy the creterion of "Data sampled: to: 2020-01-02" (which means that end of the sampling interval has to be less than 2020-01-02T00:00:00Z).
More data has been uploaded to this data specification, so reproducing the reported behavior is not possible exactly, but can be done in principle by using the "Show deprecated objects" advanced option.

**Comment by claudiodonofrio** [comment]
edited the original issue text to clarify the problem.

**Comment by mirzov** [comment]
Addressed in https://github.com/ICOS-Carbon-Portal/data/commit/90ef70546dfaa56d19579d148d16df2e6058202f
