### ISSUE TITLE
NetCDF preview doesn't work for this file

### ISSUE THREAD

**Issue by jonathanthiry** [ICOS-Carbon-Portal/data#12]
https://data.icos-cp.eu/portal/#preview?objId=CuQXUTAfNPbuEAOdFfOP3w3-

**Comment by roger-groth** [comment]
New url: https://data.icos-cp.eu/netcdf/CuQXUTAfNPbuEAOdFfOP3w3-
NetCDF file does not have a time dimension. Dump of header:

netcdf CuQXUTAfNPbuEAOdFfOP3w3- {
dimensions:
	longitude = 360 ;
	latitude = 180 ;
variables:
	double latitude(latitude) ;
		latitude:comment = "center of interval" ;
		latitude:long_name = "latitude" ;
		latitude:standard_name = "latitude" ;
		latitude:units = "degrees_north" ;
		latitude:actual_range = -89.5, 89.5 ;
	double longitude(longitude) ;
		longitude:comment = "center of interval" ;
		longitude:long_name = "longitude" ;
		longitude:standard_name = "longitude" ;
		longitude:units = "degrees_east" ;
		longitude:actual_range = -179.5, 179.5 ;
	double regionmask(latitude, longitude) ;
		regionmask:comment = "mask representing the Amazon region" ;

It fails in the preview app on https://data.icos-cp.eu/netcdf/listDates?service=CuQXUTAfNPbuEAOdFfOP3w3-

**Comment by mirzov** [comment]
This file's data are not shaped according to what our preview app can handle. This may be solved if we create a sufficiently advanced metadata model for netcdf, which the preview app could use to read the file. In the meanwhile, we now have a new "[project](http://meta.icos-cp.eu/resources/projects/notAssociated)" for data object specs of non-standard data objects. They will be hidden from search.
