### ISSUE TITLE
[stats] Add back end support for querying download stats of a single object

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/data#129]
This is needed by meta to use in the stats infobox of the landing pages. It is still relying on RestHeart for both download- and preview counts. This should probably be done by adding optional field `dobj: Option[Sha256Sum]` to `StatsQueryParam`.

**Comment by roger-groth** [comment]
Closed by commit 3624511f3916471839d98c30314febde7080c231
