### ISSUE TITLE
Purge MJ12Bot downloads from the stats, if any

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/data#139]
It seems likely that the regular downloads from Germany have been done by MJ12Bot search engine. Here are the suspect IPs  running the bot:

144.76.120.197
144.76.91.79
148.251.9.145
167.114.116.38
167.114.159.99
173.249.24.3
192.151.145.178
192.99.7.128
192.99.9.25
5.9.156.20

More complete list can be obtained like so:
`root@fsicos2:/var/log/nginx# zgrep -h MJ12bot access.log* | awk '{print $1;}' | sort -u`

**Comment by atverm** [comment]
I would recommend to block this majestic crawler, it says it is robots.txt compliant.

Alex

**Comment by mirzov** [comment]
> I would recommend to block this majestic crawler, it says it is robots.txt compliant. Alex 

Already did it in b26cb72d

**Comment by mirzov** [comment]
It turns out that the bot was not responsible for any downloads, despite repeatably calling the /licence_accept URLs for multiple data objects.
