### ISSUE TITLE
Fix NetCDF preview legend

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/data#14]
The Unit for the selected variable should be visible on the legend on the right hand side.
The legend itself should NOT change min/max with every time step.
Min/Max should be from ALL time steps and the colour is then changing accordingly to that scale.

**Comment by claudiodonofrio** [comment]
Just wondering if we have a timeline to fix this. If I can help, please let me know.

**Comment by claudiodonofrio** [comment]
Hi
I have a little scala/java program to extract the min/max values from a netcdf file, returning a json representation. Have a look at https://github.com/claudiodonofrio/netcdfminmax
 I think there are three possibilities:
1: we save an additional file for each netcdf file with the min/max values, can be accessed from the frontend
2: we extract the min/max values on demand for the frontend
3: we extend the metadata for netcdf files with "varname, min, max"

Could we have a discussion if that would be a way forward to fix the "changing" minmax value in the preview?

**Comment by jonathanthiry** [comment]
Requires #87

**Comment by mirzov** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/data/commit/ded1a9fb03e1cb8b6ebf4b704873a811f8a0ad88
