### ISSUE TITLE
[stats] Stats CSV download fails if query terms are selected

### ISSUE THREAD

**Issue by squaregoldfish** [ICOS-Carbon-Portal/data#152]
On the https://data.icos-cp.eu/stats/ page, clicking the "Download Statistics in CSV format" button fails if any search criteria are entered in the top fields. When no criteria are entered, the download works fine.

For example, with these criteria:
![Screenshot 2021-02-23 at 16 08 25](https://user-images.githubusercontent.com/733650/108864159-38c67e00-75f2-11eb-9f21-5368b6ad2a6e.png)

The following Javascript error is reported:
<img width="473" alt="Screenshot 2021-02-23 at 16 08 32" src="https://user-images.githubusercontent.com/733650/108864174-3bc16e80-75f2-11eb-9999-765d3f35eea8.png">

The effect is the same whichever criteria are selected, with a different property listed.

**Comment by roger-groth** [comment]
Thank you for an excellent error report. Made it easier to find the problem.
