### ISSUE TITLE
Station landing page in html, documentation links more user friendly

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/data#166]
Documentation items on the html version of the station landing  are shown as link to landing page of a document. Would be more user friendly to show this as an optional label that links to the access URL of the document.

**Comment by mirzov** [comment]
Easy-to-remember rule for future issue reporting: issues related to services hosted on meta.(icos-cp.eu | fieldsites.se) should be reported to GitHub repository [meta](https://github.com/ICOS-Carbon-Portal/meta). This repository (data) is for services hosted on data.(icos-cp.eu | fieldsites.se).

**Comment by eee-ea** [comment]
Wow that's too complicated for me 😖. Sorry for the mistake.

Alex

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jonathanthiry** [comment]
Thanks for taking care of this @mirzov ! It's possible to transfer issues between repos, I'll move this one to meta as an example.
