### ISSUE TITLE
Fail to connect to B2SAFE in dryRun

### ISSUE THREAD

**Issue by jonathanthiry** [ICOS-Carbon-Portal/data#168]
B2SafeUploadTask tries to connect to B2SAFE with dryRun config and [throws an error](https://github.com/ICOS-Carbon-Portal/data/blob/master/src/main/scala/se/lu/nateko/cp/data/services/upload/B2SafeUploadTask.scala#L46) when the password is not provided.

**Comment by mirzov** [comment]
The issue is somewhat controversial, by the way, as the idea of dry-run was not to prevent the client from talking to the service, but only to prevent it from making any changes in the B2SAFE storage.
