### ISSUE TITLE
[portal] Expose link to CSV download in the tabular data preview view

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/data#170]
The functionality should be available on the same level as the "Copy preview chart URL" button. The API for CSV download is described [here](https://github.com/ICOS-Carbon-Portal/data#csv-download-for-tabular-time-series-data).

An important additional requirement is to include flag/QC columns, where applicable, into the CSV download link.

**Comment by roger-groth** [comment]
Closed by https://github.com/ICOS-Carbon-Portal/data/commit/a7b6b5cd8a3effe14a6439ece3e3785695e865d7
