### ISSUE TITLE
Check consistency of metadata and data filenames

### ISSUE THREAD

**Issue by ukarst** [ICOS-Carbon-Portal/data#23]
Check for consistent information in the different services, eg. measurement height at SMEAR/Hyytiälä station is different in 'provisional stations', station table' and filename of the data file.
http://meta.icos-cp.eu/ontologies/stationentry/AS/ATM-HYY
https://meta.icos-cp.eu/objects/KPZrKXYMzWM824UaIUYHEwf-

**Comment by mirzov** [comment]
Provisional stations are provided by the HO, and stations table app used that metadata (plus labeling), but the data objects uploaded to CP come from the thematic centers, who are the authoritative source of metadata about the stations. The idea is that the provisional stations meta is only used to bootstrap the station inclusion process at TCs, so we do not really need to (and are not responsible for) provide consistency between these two views.
