### ISSUE TITLE
netcdf preview with pre-defined gamma

### ISSUE THREAD

**Issue by ukarst** [ICOS-Carbon-Portal/data#24]
Would be good to start the preview of netcdf files with a pre-defined setting for gamma. Default could be 1 (like it is now) but for some datasets, like the CO2 emisssions it would be useful to set this to 0.1 when starting the preview, otherwise the user might not easily know why nothing shows up on the map.

**Comment by ukarst** [comment]
An even better option than using the gamma would be a logarithmic color scale. Investigating the histogram of all values might be used to automatically decide whether to use a linear or logarithmic color scale.

**Comment by roger-groth** [comment]
Example of default gamma 1: https://data.icos-cp.eu/portal/#%7B%22route%22%3A%22preview%22%2C%22preview%22%3A%5B%22yVN6HhNF4m5Z9BNgwVmoT4yA%22%5D%7D

Example of default gamma 0.1: https://data.icos-cp.eu/portal/#%7B%22route%22%3A%22preview%22%2C%22preview%22%3A%5B%226T0zQII1VzJHDmJLSZU5s4qE%22%5D%7D

**Comment by jonathanthiry** [comment]
This was solved by making the color scale stay constant during the preview.
