### ISSUE TITLE
Document metadata like Title, Description is not shown at document landing page. Should be added

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/data#245]
Relevant metadata like Title, Description should be added to document object landing page

**Comment by jonathanthiry** [comment]
Could you give an example where it doesn't work?
It works fine for https://meta.icos-cp.eu/objects/0JnFcRcp5vbLtbs9e0C-VhMQ for example.

**Comment by jonathanthiry** [comment]
Works as intended.
Document metadata can be specified during upload and is shown on the landing page.
