### ISSUE TITLE
Data object preview not available in cart

### ISSUE THREAD

**Issue by klarakristina** [ICOS-Carbon-Portal/data#260]
The preview button of data objects in the cart is greyed out although the object is selected, as seen in the example:

![Screenshot 2022-08-09 at 15-16-07 ICOS data search](https://user-images.githubusercontent.com/21019121/183656949-a6dd999e-e697-4eb3-9483-728f20f11f3b.png)

**Comment by jonathanthiry** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/data/commit/5474920ec4948093f0fce872fccefc04afa163b4
