### ISSUE TITLE
Preview of netcdf spatial data color scale update

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/data#263]
Preview of netcdf spatial data still needs a user settable persistent (symmetric) min-max scale for the color scale and needs color scale palettes similar to siesmic, rainbow, gist_rainbox, cubehelix, turbo. See https://matplotlib.org/stable/tutorials/colors/colormaps.html

**Comment by mirzov** [comment]
Implemented in https://github.com/ICOS-Carbon-Portal/data/commit/9ba2b5cb671651471c2ad2fdae9967781a7a6c1e and c647d692
