### ISSUE TITLE
Style ICOS Cities portal

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/data#296]
Header as in 
https://citydata1.icos-cp.eu/portal/

Copied that as png in https://fileshare.icos-cp.eu/apps/files/?dir=/PAUL/materials&fileid=3036589

Footer like in https://fileshare.icos-cp.eu/apps/files/?dir=/PAUL/materials&openfile=3036688

Menu could be the six items from the six picture buttons on https://www.icos-cp.eu/projects/icos-cities.

**Comment by jonathanthiry** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/data/commit/eb57db88f602951292bfa75689b86edc74a54ee3, https://github.com/ICOS-Carbon-Portal/cpauth/commit/3a991283778ad3f4f6619bc56f2e8cf5552db07f, and https://github.com/ICOS-Carbon-Portal/meta/commit/3360e516fc861c1653553e8cbcf1a4e4b90fd553
