### ISSUE TITLE
[icos_cp_core] code documentation 

### ISSUE THREAD

**Issue by altix** [ICOS-Carbon-Portal/data#315]
PEP-8 suggest 72 characters for a line in the doc-string of a python member. 

Some, objects are not documented where they are created, Instead they are explained in other places.  
To document them where they are created would be prefered in case the objects are used elsewhere in the future.

**Comment by mirzov** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/data/commit/e6a05f4130815c9fbd0e23ce90fae707c39dd5ea
