### ISSUE TITLE
Data statistics retrieval by python fails in parsing the json info

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/data#318]
![VirtualBox_Ubuntu_05_03_2024_09_48_47](https://github.com/ICOS-Carbon-Portal/data/assets/10813804/d09d717f-cd3e-4646-901e-ac5ff787c205)

Call to restheart works and seems to deliver correct json data, but parsing fails. See screenshot.

**Comment by Jonathan-Schenk** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/infrastructure/commit/6499fd7fc521e39e38a957fd6cf26d67974379b4
