### ISSUE TITLE
ICOS StationMap

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/data#32]
When zooming out of the station map, the "world" map is not displayed. Hence not all "ICOS" stations are visible. For example La Reunion or Cape Verde.

**Comment by eee-ea** [comment]
That is as designed. The Lambert conformal conic projection does not work well outside Europe using the library that was used here. More info: https://en.wikipedia.org/wiki/Lambert_conformal_conic_projection. In other projections like WGS84 or Mercator the maps scales well for the whole world. e.g.: https://www.ingos-infrastructure.eu/icos/test.html

**Comment by claudiodonofrio** [comment]
We should change the library then, i think it is more important to show all stations, rather then having the perfect projection. I have done one with python writing JS with leaflet, and that works fine for me.

**Comment by atverm** [comment]
Try there the lambert conformal projection then. As the example shows this library can do it in other projection. However we choose to display the data in the projection advised by the EU. Please talk also with Roger who implemented this.

Alex

**Comment by claudiodonofrio** [comment]
yep, no blame to the "library", but that's not the point.
I think a user coming to the website, looking at a map of  "all icos stations", would like to see all icos stations, and not 90% of the stations. Maybe this is a discussion we can continue in the team meeting, since it is not a technical problem.
