### ISSUE TITLE
Page summarizing the L2 collections seems to no longer be linked on the CP web site?

### ISSUE THREAD

**Issue by DrMaggie** [ICOS-Carbon-Portal/data#40]
I was looking for the page with the summary table and links to the atmospheric L2 collections - but was unable to find it. Considering the increased interest in these datasets from the ICOS end user communities, there should be a very clear and easy-to-find link from e.g. the "discover our data" page (https://www.icos-cp.eu/data). (And optimally the collections should be searchable via the Advanced Search page - see issue #39 https://github.com/ICOS-Carbon-Portal/data/issues/39)

**Comment by DrMaggie** [comment]
Ah, thanks to Alex I was able to identify the page that I was referring to: " NRT CO2 and CH4 mole fraction growing time series at ICOS stations" (https://www.icos-cp.eu/atm_nrt_co2_ch4).

At the moment, this seems to be only linked via the ICOS Data Products page (https://www.icos-cp.eu/dataproducts), and it's not at all clear from that page what kind of info one will see by following the link to https://www.icos-cp.eu/atm_nrt_co2_ch4. 

This is actually a static landing page for the DOI https://doi.org/10.18160/ATM_NRT_CO2_CH4. I had somehow forgotten that we have chosen to treat the collection as a dynamic dataset. (Not really FAIR, which leads to the need to formulate a new issue on its own merit...)

I think we need to be much more explicit & clear, especially now that ICOS has entered into the "need to deliver data & metadata" phase. One way to summarize our holdings of ICOS data could be to have overview tables like the one on https://www.icos-cp.eu/atm_nrt_co2_ch4, but broken down to indicate yearly availability, available via links from https://www.icos-cp.eu/data - and not just for L2 but also for the other Ls.

**Comment by mirzov** [comment]
This GitHub project covers products and services offered via web domain address data.icos-cp.eu. Our Drupal webpage is served under www.icos-cp.eu, and therefore the issue probably belongs to [drupal](https://github.com/ICOS-Carbon-Portal/drupal) project or perhaps, considering that it is not directly actionable, maybe the best venue would have been email in this case. Shall I close the issue?
