### ISSUE TITLE
Data set "titles" in the search results tab should be more verbose

### ISSUE THREAD

**Issue by DrMaggie** [ICOS-Carbon-Portal/data#41]
Currently, a search for e.g. ICOS atmospheric L2 data (https://data.icos-cp.eu/portal/#%7B%22filterCategories%22%3A%7B%22project%22%3A%5B%22icos%22%5D%2C%22theme%22%3A%5B%22atmosphere%22%5D%2C%22level%22%3A%5B2%5D%7D%7D) results in a list of datasets (in the "Search results" tab) which are titled according to their "Data Type" - for example "ICOS ATC CH4 Release" or "ICOS ATC MTO Release". 
These titles are now presented in a larger font, and with a bright blue color, that catches the eyes. However, the complementary information that an end user will need to be able to make a first, basic distinction between the different returned items - such as station name and dates covered in the dataset - are presented in a crowded row where many different metadata attributes are listed together in a much smaller font, 
I suggest to use the same approach to prepare & show a longer, more comprehensive dataset title, following the recipe that is now used for the citation strings found on landing pages. Examples of such more descriptive titles (here for L2 data sets) are "ICOS ATC CH4 Release, Gartow (216.0 m), 2017-04-11-2018-05-31" and "ICOS ATC MTO Release, Hyltemossa (150.0 m)". 
We could IMHO put this in larger blue font, and the add the "data type" to the row below, if it is needed, e.g. putting it (+ an appropriate mini-icon) just after the domain indication (e.g.  Atmospheric data).
In case the title string becomes too long, perhaps the station abbreviation could be used instead, i.e. "ICOS ATC CH4 Release, GAT (216.0 m), 2017-04-11-2018-05-31" - but that would obviously not be as informative.
Correspondingly, on the "Compact view" tab, the tool tip generated when hovering over the data set file name link should of course also be modified to use the same dataset title as in the other tab.

**Comment by mirzov** [comment]
This approach is possible to implement exactly only for ICOS atmospheric data of L1 and L2. No other data objects have sampling height associated with them. No L3 data in general have any association with stations. How would we go about those?

**Comment by jonathanthiry** [comment]
Fixed by d4924fcf4b16acd8f161d734b17fa596e511fcf3
