### ISSUE TITLE
Would like to have measurement level next to station name in list, not at end of list 

### ISSUE THREAD

**Issue by eee-ea** [ICOS-Carbon-Portal/data#47]

**Comment by eee-ea** [comment]
Why was this closed?

**Comment by roger-groth** [comment]
Thought it was fixed. Can you explain what list you are talking about?

**Comment by atverm** [comment]
This explains better what I meant, I Hope.

Alex

**Comment by roger-groth** [comment]
Actually, it doesn't. Perhaps something was lost when you emailed?

**Comment by roger-groth** [comment]
Result: https://data.icos-cp.eu/portal/#{%22filterCategories%22%3A{%22theme%22%3A[%22atmosphere%22]%2C%22project%22%3A[%22ingos%22]}}

**Comment by atverm** [comment]
Yes! Thanks a lot. Small leaps sometimes make great results.
