### ISSUE TITLE
netcdf download failed

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/data#51]
The data file https://meta.icos-cp.eu/objects/II93UyEd61Gdp_lXwgRqrS4W
can be "previewed" but if I download the file, the zip file is empty. I'am aware that the data is not ICOS, but strange that we have the preview, but can't download. The corresponding link on the landing page leads to a website, where a "login" is required (https://apps.ecmwf.int/datasets/data/cams-ghg-inversions/).
In general we should check if a "data" file is availalbe to prevent the user of downloading an empty zip file.

**Comment by atverm** [comment]
If you click the Access URL on the landing page you will be referred to the COPERNICUS CAMS page where you need to login and accept their data license first. This works as designed and required.

Alex

**Comment by claudiodonofrio** [comment]
I am aware of that, but maybe we should "prevent" the download of an empty zip file?

**Comment by mirzov** [comment]
Direct, unofficial download of this data object actually works. Downloading a data cart containing only this object also works, and results not in an empty zip file, but in a zip archive with two files: licence and table of contents. The latter lists all the files in the cart, and the reason for omission of the missing ones. The behaviour is as designed.

**Comment by jonathanthiry** [comment]
This behavior can be surprising as the portal doesn't mention that the data will not be downloaded. The cart even reports a download size of 152.03 MB for this object which hints that the data will be inside the zip.

I would suggest to display the actual size of the cart by counting only the files included in the zip. The data portal could also display in the results/cart that the file is available for download only though the external link.

**Comment by atverm** [comment]
I would suggest that we for this we include as planned license info in the data object specification metadata. ICOS data gets a CC4BY license spec and URL and is handled through the ICOS license check. Objects with other (and limiting) licenses get a referral to their own license check/login/repo. All CC0 and free objects just go straight into the cart. An item OtherLicenseInfo can be used as help text in the search result to show that this file cannot be downloaded directly (download checkbox greyed out) and that the user will be referred to an external site. Level 0 data would get this info as for example: This data is available on request from Thematic Center at info@icos-etc.eu<mailto:info@icos-etc.eu>. The license info could be shown as a little icon in the search result.

Alex
