### ISSUE TITLE
Portal app: add href html attributes to the links in the dobj search result list

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/data#74]
Users have expressed interest in being able to open metadata views of data objects in separate tabs. Currently, this is not possible, as the links are not complete (lack href attribute), so right-clicking on them does not give the option of opening in new tab. Investigate a possibility of adding the href attributes, but intercepting the left-click behavior, so that the app behaves as usual.

**Comment by mirzov** [comment]
The compact view should also get this enhancement.

**Comment by jonathanthiry** [comment]
Also <kbd>ctrl</kbd> + <kbd>click</kbd> should only open the metadata in the new tab, not the current one.
