### ISSUE TITLE
Level 0 shouldn't be selectable in the portal

### ISSUE THREAD

**Issue by jonathanthiry** [ICOS-Carbon-Portal/data#75]
It became possible to select and add to cart level 0 data. The checkbox should be grayed out for these objects.

https://data.icos-cp.eu/portal/#%7B%22filterCategories%22%3A%7B%22level%22%3A%5B%220%22%5D%7D%7D

**Comment by mirzov** [comment]
@roger-groth This could be related to #73 due to data level somehow becoming string instead of a number, which probably have happened during Typescript rewrites.
