### ISSUE TITLE
download statistics no results returned

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/data#77]
the filter / selection of "THEME" leads to unreasonable or no results.
For example:
Select Station Norunda -> Downloads per year for 2019 -> approx. 20'000
Select station Norunda & Atmosphere -> 0 downloads for 2019
Select station Norunda & Ecosystem -> 0 downloads for 2019

**Comment by roger-groth** [comment]
We may have reached end of the line with the MongoDB log. This issue is put on hold until further notice to discuss our options.

**Comment by claudiodonofrio** [comment]
What does that mean? Has it other implications?

**Comment by mirzov** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/data/commit/1bf27153d2be694590ed6eae24bdffe840383db1
