### ISSUE TITLE
Error with unzip datafile on Windows OS

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/data#78]
Unzip Data File Error on Windows OS

- Download Data, for example https://data.icos-cp.eu/objects/3J6Zj4rmvSDHCIcL_ETaWzlQ
- Use the windows inbuilt unzip program (Extract All)
  - Error: Parameter is incorrect
    - If you press cancel only 1 file is extracted, with the semicolon in the filename stripped
    - If you press skip: all files are extracted with all semicolons stripped
- Use 7-zip to extract the same zip archive.
  - No error, but all semicolons are stripped

[Unzip Data File Error on Windows OS.pdf](https://github.com/ICOS-Carbon-Portal/data/files/3762016/Unzip.Data.File.Error.on.Windows.OS.pdf)

The official Microsoft documentation about filenames can be found here:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#file-and-directory-names

characters which are NOT allowed:

- &#60; (less than)
- &#62; (greater than)
- : (colon)
- " (double quote)
- / (forward slash)
- \ (backslash)
- &#124; (vertical bar or pipe)
- ? (question mark)
- &#42; (asterisk)

**Comment by mirzov** [comment]
ATC has changed their file naming convention, so that the problematic characters are not used in the file names any more.
